services:
  agentai-app:
    build: .
    container_name: agentai-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - PYTHONUNBUFFERED=1
