when:
  - event: push

steps:
  - name: build and push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ghcr.io/siberianbearofficial/scheduleai-bff
      registry: ghcr.io
      username: siberianbearofficial
      password:
        from_secret: GITHUB_TOKEN
      context: bff
      tag: main

  - name: deploy
    image: curlimages/curl
    commands:
      - curl -X 'POST' 'https://deploy-api.nachert.art/api/v1/stacks/schedule-ai/deployments' -H $${AUTH_HEADER}
    environment:
      AUTH_HEADER:
          from_secret: DEPLOY_API_CREDENTIALS
