when:
  - event: push

steps:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      lfs: false

  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ghcr.io/siberianbearofficial/scheduleai-bff
      registry: ghcr.io
      username: siberianbearofficial
      password:
        from_secret: GITHUB_TOKEN
      dockerfile: bff/ScheduleAI.Api/Dockerfile
      context: bff/ScheduleAI.Api
      tags:
        - main
      auto_tag: true
      labels:
        - "org.opencontainers.image.revision=${WOODPECKER_COMMIT_SHA}"
        - "org.opencontainers.image.source=https://github.com/siberianbearofficial/scheduleai"

  - name: deploy
    image: curlimages/curl
    commands:
      - curl -X 'POST' "${DEPLOY_URL}" -H "${DEPLOY_CREDS}"
    environment:
      - DEPLOY_URL: 'https://deploy-api.nachert.art/api/v1/stacks/schedule-ai/deployments'
      - AUTH_HEADER:
          from_secret: DEPLOY_API_CREDENTIALS
