when:
  - event: push

steps:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      lfs: false

  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ghcr.io/siberianbearofficial/scheduleai-bff
      registry: ghcr.io
      username: siberianbearofficial
      password: ${GITHUB_TOKEN}
      dockerfile: bff/ScheduleAI.Api/Dockerfile
      context: bff/ScheduleAI.Api
      tags:
        - main
      auto_tag: true
      labels:
        - "org.opencontainers.image.revision=${WOODPECKER_COMMIT_SHA}"
        - "org.opencontainers.image.source=https://github.com/siberianbearofficial/scheduleai"
    secrets: [ GITHUB_TOKEN ]

  - name: deploy
    image: alpine
    commands:
      - apk add curl
      - curl -X POST \
          'https://deploy-api.nachert.art/api/v1/stacks/schedule-ai/deployments'  \
          -H 'accept: application/json' \
          -H "Authorization: Basic ${DEPLOY_API_CREDENTIALS}" \
          -d ''
    secrets: [ DEPLOY_API_CREDENTIALS ]
